Add a missing call and missing options to nock index.d.ts (#35166)
* Bumped ver to 10.0.1

nock.activeMocks() is missing => added function activeMocks(): string[]; to the nock namespace.
nock( 'https://api.github.com' , {"encodedQueryParams":true}) => added encodedQueryParams: boolean to the Options interface.

* Updated per previous comments

However, I don't know what this error is that is causing Travis CI to fail???
```
Error: ../node/v7/index.d.ts: Definitions must use global references to other packages, not parent ("../xxx") references.(Based on reference 'base.d.ts')
```

* Update tests for activeNocks

* Dedent/remove 'function' from activeMocks in Scope interface

* linter changes