[pouchdb-core] Fix Blob interface by including dom (#29755)
* [pouchdb-core] Fix Blob interface by including dom

error TS2304: Cannot find name 'Blob'

* [pouchdb-core] duplicate Blob interface inline (#1)

Forward declare Blob instead of using a triple-slash directive.
/// <reference types="dom"> looks for 'dom' in Definitely Typed, but the 'dom' lib is built into TypeScript.